### ISSUE TITLE
Parameter and wildcard matches are decodeURIed twice

### ISSUE THREAD

**Issue by kylewm** [Medium/matador#171]
Tracking down [a bug in medium2](https://github.com/Medium/medium2/issues/33473#issuecomment-227917834), I noticed matador is unescaping parameters one too many times. For example, if 

1. there's a route `/dir/*` 
2. client wants to send the parameter `http://hi%5Ethere` 
3. client hits the path `/dir/http%3A%2F%2Fhi%255Ethere`
4. matador tells me `*` is `http://hi^there` (`^` should be `%5E`)

I added a test demonstrating: https://github.com/Medium/matador/compare/kylewm/over-decoding with the result:

```
✖ testNamedParameterEscaping

AssertionError: 'hello%20world' == 'hello world'
    at Object.equal (/Users/kylemahan/src/matador/node_modules/nodeunit/lib/types.js:83:39)
    at /Users/kylemahan/src/matador/tests/functional/routing_test.js:17:10
    ...

✖ testWildcardEscaping

AssertionError: 'http://example.com/abc%5E123' == 'http://example.com/abc^123'
    at Object.equal (/Users/kylemahan/src/matador/node_modules/nodeunit/lib/types.js:83:39)
    at /Users/kylemahan/src/matador/tests/functional/routing_test.js:31:10
    ...
```

**Comment by kylewm** [comment]
I *think* it's safe to [remove the extra calls to decodeURI](https://github.com/Medium/matador/commit/1f917057c7a42cc6405eb1f407e31b15e839be07) ... and Medium's graph-tests still pass without it. 

@majelbstoat @nicks do you have context on this to advise? (sorry, I know it's a hot path through old code...bad combination)

**Comment by majelbstoat** [comment]
Oh man, I don't remember the context on this. It was something to do with media resources though, I'm pretty sure. If all the tests in medium2 pass on it, including functional tests, then let's go for it, asked if it breaks something, we can write more tests for that. Hard to know the full impact, but if there's a bug that this fixes, this seems reasonable.

**Comment by nicks** [comment]
sgtm. if you change something, and no tests break, then it must be a safe
change!

**Comment by kylewm** [comment]
@majelbstoat @nicks thanks for taking a look! would you mind releasing a new version on npm when you have a chance?

**Comment by nicks** [comment]
published!

**Comment by kylewm** [comment]
Thanks! :fire:
